<?php
// This file is part of MuTMS suite of plugins for Moodle™ LMS.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// phpcs:disable moodle.Files.BoilerplateComment.CommentEndedTooSoon

namespace tool_mulib\local;

use core\exception\coding_exception;

/**
 * Class loader for libraries bundled in plugin vendor directories.
 *
 * Plugins ship their Composer libraries in their own vendor/ directory, but they must never
 * include vendor/autoload.php: every Composer autoloader registers itself in front of all
 * other loaders, the plugin then becomes the Composer root package for the rest of the request
 * (Composer\InstalledVersions::getRootPackage()) and its copies of shared packages shadow
 * the ones installed by Moodle. This loader reads the maps generated by Composer
 * (vendor/composer/autoload_*.php) and appends a plain class loader after all existing loaders,
 * so Moodle always wins for packages it has, and Composer runtime state is left alone.
 *
 * @package     tool_mulib
 * @copyright   2026 Petr Skoda
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
final class vendor_loader {
    /** @var array vendor directories already registered */
    private static array $registered = [];

    /**
     * Register class loading of a plugin vendor directory, repeated calls do nothing.
     *
     * @param string $vendordir path to the vendor directory generated by Composer
     */
    public static function register(string $vendordir): void {
        $realdir = realpath($vendordir);
        if ($realdir === false || !is_dir($realdir . '/composer')) {
            throw new coding_exception('Invalid Composer vendor directory: ' . $vendordir);
        }
        if (isset(self::$registered[$realdir])) {
            return;
        }
        self::$registered[$realdir] = true;

        $classmap = self::read_map($realdir . '/composer/autoload_classmap.php');
        $psr4 = self::read_map($realdir . '/composer/autoload_psr4.php');
        $psr0 = self::read_map($realdir . '/composer/autoload_namespaces.php');
        // The most specific prefix wins, the same as in Composer.
        uksort($psr4, fn(string $a, string $b): int => strlen($b) <=> strlen($a));
        uksort($psr0, fn(string $a, string $b): int => strlen($b) <=> strlen($a));

        spl_autoload_register(function (string $class) use ($classmap, $psr4, $psr0): void {
            if (isset($classmap[$class])) {
                require_once($classmap[$class]);
                return;
            }
            foreach ($psr4 as $prefix => $dirs) {
                if (!str_starts_with($class, $prefix)) {
                    continue;
                }
                $relative = str_replace('\\', '/', substr($class, strlen($prefix))) . '.php';
                foreach ((array)$dirs as $dir) {
                    if (is_file($dir . '/' . $relative)) {
                        require_once($dir . '/' . $relative);
                        return;
                    }
                }
            }
            foreach ($psr0 as $prefix => $dirs) {
                if (!str_starts_with($class, $prefix)) {
                    continue;
                }
                $relative = str_replace(['\\', '_'], '/', $class) . '.php';
                foreach ((array)$dirs as $dir) {
                    if (is_file($dir . '/' . $relative)) {
                        require_once($dir . '/' . $relative);
                        return;
                    }
                }
            }
        }, true, false);

        // Files are shared with Composer through the same global registry, each is included once only.
        foreach (self::read_map($realdir . '/composer/autoload_files.php') as $identifier => $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$identifier])) {
                $GLOBALS['__composer_autoload_files'][$identifier] = true;
                require($file);
            }
        }
    }

    /**
     * Read a map generated by Composer.
     *
     * @param string $file
     * @return array
     */
    private static function read_map(string $file): array {
        if (!is_file($file)) {
            return [];
        }
        $map = require($file);
        return is_array($map) ? $map : [];
    }
}
